CREATE TABLE IF NOT EXISTS profiles(
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  firstname VARCHAR(100) NOT NULL DEFAULT '',
  lastname VARCHAR(160) NOT NULL DEFAULT ''
);