apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template: 
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: auth-service-app
          image: ghcr.io/go-dev-space/auth-service:latest 
          livenessProbe:
            httpGet:
              path: /v1/auth/healthcheck
              port: 8080
              httpHeaders:
                - name: "X-Access-Header"
                  value: "2cf24dba5fb"
            periodSeconds: 10
            initialDelaySeconds: 5
