name: Audit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Audit project   
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main  
      
      - name: Setup Go
        uses: actions/setup-go@v5    
        with:
          go-version: 1.24.2

      - name: Verify Dependecies
        run: go mod verify

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -o bin/main ./cmd/api/*.go

      - name: Run go vet
        run: go vet ./...  

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run Tests
        run: go test -race ./...  
