name: Build
on:
  workflow_run:
    workflows: ["Audit"]
    types:
      - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Build project

    steps:
      - name: Checkout commit from triggering workflow
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Install sops and gpg
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg
          curl -Lo sops https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          chmod +x sops && sudo mv sops /usr/local/bin/ 
        
      - name: Import GPG key for SOPS
        run: |
          echo "${{ secrets.SOPS_GPG_KEY }}" > private.asc
          gpg --batch --import private.asc    

      - name: Decrypt .env.enc
        run: |
          sops -d --input-type dotenv --output-type dotenv .env.enc > .env   
          
      - name: Setup Go
        uses: actions/setup-go@v5    
        with:
          go-version: 1.24.2  
          
      - name: Build Docker image and push to registry
        env:
          GITHUBTOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo $GITHUBTOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build -f docker/Dockerfile -t ghcr.io/go-dev-space/auth-service:latest .
          docker push ghcr.io/go-dev-space/auth-service:latest      
