name: Build
on:
  workflow_run:
    workflows: ["Audit"]
    types:
      - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Build project

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Setup Go
        uses: actions/setup-go@v5    
        with:
          go-version: 1.24.2  
          
      - name: Build Docker image and push to registry
        env:
          GITHUBTOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUBTOKEN
          docker build . --tag ghcr.io/go-dev-space/auth-service:latest
          docker push ghcr.io/go-dev-space/auth-service:latest      
